//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_loadorb_H
#define METASPRITE_loadorb_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define loadorb_TILE_ORIGIN 0
#define loadorb_TILE_H 8
#define loadorb_WIDTH 32
#define loadorb_HEIGHT 32
#define loadorb_TILE_COUNT 27
#define loadorb_PIVOT_X 16
#define loadorb_PIVOT_Y 16
#define loadorb_PIVOT_W 32
#define loadorb_PIVOT_H 32

BANKREF_EXTERN(loadorb)

extern const palette_color_t loadorb_palettes[12];
extern const uint8_t loadorb_tiles[432];

extern const metasprite_t* const loadorb_metasprites[8];

#endif