//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_loadorb_invert_H
#define METASPRITE_loadorb_invert_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define loadorb_invert_TILE_ORIGIN 0
#define loadorb_invert_TILE_H 8
#define loadorb_invert_WIDTH 32
#define loadorb_invert_HEIGHT 32
#define loadorb_invert_TILE_COUNT 26
#define loadorb_invert_PIVOT_X 16
#define loadorb_invert_PIVOT_Y 16
#define loadorb_invert_PIVOT_W 32
#define loadorb_invert_PIVOT_H 32

BANKREF_EXTERN(loadorb_invert)

extern const palette_color_t loadorb_invert_palettes[12];
extern const uint8_t loadorb_invert_tiles[416];

extern const metasprite_t* const loadorb_invert_metasprites[8];

#endif