/*

 THROBBER_DATA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 32 x 32
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : Yes.
  Index offset         : 0
  Index counter        : None.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define throbberBank 0
/* Metatile index */
extern const unsigned char throbberIndex[];

extern const metasprite_t* const throbber_metasprites[8];

/* Start of tile array. */
extern const unsigned char throbber[];

/* End of THROBBER_DATA.H */
