/*

 TESTINGDOORS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\bullr\Documents\gameboy\bruh.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 21
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TestingRoomDoorsWidth 20
#define TestingRoomDoorsHeight 18
#define TestingRoomDoorsBank 0

extern unsigned char TestingRoomDoors[];

/* End of TESTINGDOORS.H */
