//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_abutton_H
#define METASPRITE_abutton_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define abutton_TILE_ORIGIN 0
#define abutton_TILE_H 8
#define abutton_WIDTH 32
#define abutton_HEIGHT 32
#define abutton_TILE_COUNT 16
#define abutton_MAP_ATTRIBUTES 0
#define abutton_TILE_PALS abutton_tile_pals

BANKREF_EXTERN(abutton)

extern const palette_color_t abutton_palettes[4];
extern const uint8_t abutton_tiles[256];

extern const unsigned char abutton_map[16];
extern const unsigned char* abutton_tile_pals[16];

#endif