//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_arrow_H
#define METASPRITE_arrow_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define arrow_TILE_H 16
#define arrow_WIDTH 16
#define arrow_HEIGHT 16
#define arrow_TILE_COUNT 2
#define arrow_PIVOT_X 8
#define arrow_PIVOT_Y 8
#define arrow_PIVOT_W 16
#define arrow_PIVOT_H 16

BANKREF_EXTERN(arrow)

extern const palette_color_t arrow_palettes[4];
extern const uint8_t arrow_tiles[64];

extern const metasprite_t* const arrow_metasprites[1];

#endif