//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bbutton_H
#define METASPRITE_bbutton_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bbutton_TILE_ORIGIN 0
#define bbutton_TILE_H 8
#define bbutton_WIDTH 32
#define bbutton_HEIGHT 32
#define bbutton_TILE_COUNT 16
#define bbutton_MAP_ATTRIBUTES 0
#define bbutton_TILE_PALS bbutton_tile_pals

BANKREF_EXTERN(bbutton)

extern const palette_color_t bbutton_palettes[4];
extern const uint8_t bbutton_tiles[256];

extern const unsigned char bbutton_map[16];
extern const unsigned char* bbutton_tile_pals[16];

#endif