//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bottomleft_H
#define METASPRITE_bottomleft_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bottomleft_TILE_ORIGIN 33
#define bottomleft_TILE_H 8
#define bottomleft_WIDTH 160
#define bottomleft_HEIGHT 128
#define bottomleft_TILE_COUNT 0
#define bottomleft_PALETTE_COUNT 1
#define bottomleft_MAP_ATTRIBUTES 0
#define bottomleft_TILE_PALS bottomleft_tile_pals

BANKREF_EXTERN(bottomleft)


extern const unsigned char bottomleft_map[320];

#endif