//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bottomright_H
#define METASPRITE_bottomright_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bottomright_TILE_ORIGIN 0
#define bottomright_TILE_H 8
#define bottomright_WIDTH 160
#define bottomright_HEIGHT 128
#define bottomright_TILE_COUNT 12
#define bottomright_PALETTE_COUNT 1
#define bottomright_MAP_ATTRIBUTES 0
#define bottomright_TILE_PALS bottomright_tile_pals

BANKREF_EXTERN(bottomright)

extern const palette_color_t bottomright_palettes[4];
extern const uint8_t bottomright_tiles[192];

extern const unsigned char bottomright_map[320];
extern const unsigned char* bottomright_tile_pals[12];

#endif