//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bricktileset_H
#define METASPRITE_bricktileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bricktileset_TILE_ORIGIN 0
#define bricktileset_TILE_H 8
#define bricktileset_WIDTH 168
#define bricktileset_HEIGHT 8
#define bricktileset_TILE_COUNT 21
#define bricktileset_PALETTE_COUNT 1

BANKREF_EXTERN(bricktileset)

extern const palette_color_t bricktileset_palettes[4];
extern const uint8_t bricktileset_tiles[336];


#endif