//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_buttonup_H
#define METASPRITE_buttonup_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define buttonup_TILE_ORIGIN 0
#define buttonup_TILE_H 8
#define buttonup_WIDTH 32
#define buttonup_HEIGHT 32
#define buttonup_TILE_COUNT 13
#define buttonup_MAP_ATTRIBUTES 0
#define buttonup_TILE_PALS buttonup_tile_pals

BANKREF_EXTERN(buttonup)

extern const palette_color_t buttonup_palettes[4];
extern const uint8_t buttonup_tiles[208];

extern const unsigned char buttonup_map[16];
extern const unsigned char* buttonup_tile_pals[13];

#endif