//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_buttonscreen_H
#define METASPRITE_buttonscreen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define buttonscreen_TILE_ORIGIN 0
#define buttonscreen_TILE_H 8
#define buttonscreen_WIDTH 160
#define buttonscreen_HEIGHT 144
#define buttonscreen_TILE_COUNT 68
#define buttonscreen_MAP_ATTRIBUTES 0
#define buttonscreen_TILE_PALS buttonscreen_tile_pals

BANKREF_EXTERN(buttonscreen)

extern const palette_color_t buttonscreen_palettes[4];
extern const uint8_t buttonscreen_tiles[1088];

extern const unsigned char buttonscreen_map[360];
extern const unsigned char* buttonscreen_tile_pals[68];

#endif