//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_buttonright_H
#define METASPRITE_buttonright_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define buttonright_TILE_ORIGIN 0
#define buttonright_TILE_H 8
#define buttonright_WIDTH 32
#define buttonright_HEIGHT 32
#define buttonright_TILE_COUNT 13
#define buttonright_MAP_ATTRIBUTES 0
#define buttonright_TILE_PALS buttonright_tile_pals

BANKREF_EXTERN(buttonright)

extern const palette_color_t buttonright_palettes[4];
extern const uint8_t buttonright_tiles[208];

extern const unsigned char buttonright_map[16];
extern const unsigned char* buttonright_tile_pals[13];

#endif