//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_buttondown_H
#define METASPRITE_buttondown_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define buttondown_TILE_ORIGIN 0
#define buttondown_TILE_H 8
#define buttondown_WIDTH 32
#define buttondown_HEIGHT 32
#define buttondown_TILE_COUNT 13
#define buttondown_MAP_ATTRIBUTES 0
#define buttondown_TILE_PALS buttondown_tile_pals

BANKREF_EXTERN(buttondown)

extern const palette_color_t buttondown_palettes[4];
extern const uint8_t buttondown_tiles[208];

extern const unsigned char buttondown_map[16];
extern const unsigned char* buttondown_tile_pals[13];

#endif