//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_buttonleft_H
#define METASPRITE_buttonleft_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define buttonleft_TILE_ORIGIN 0
#define buttonleft_TILE_H 8
#define buttonleft_WIDTH 32
#define buttonleft_HEIGHT 32
#define buttonleft_TILE_COUNT 13
#define buttonleft_MAP_ATTRIBUTES 0
#define buttonleft_TILE_PALS buttonleft_tile_pals

BANKREF_EXTERN(buttonleft)

extern const palette_color_t buttonleft_palettes[4];
extern const uint8_t buttonleft_tiles[208];

extern const unsigned char buttonleft_map[16];
extern const unsigned char* buttonleft_tile_pals[13];

#endif