//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_dmgtitlescreen_H
#define METASPRITE_dmgtitlescreen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define dmgtitlescreen_TILE_ORIGIN 0
#define dmgtitlescreen_TILE_H 8
#define dmgtitlescreen_WIDTH 160
#define dmgtitlescreen_HEIGHT 144
#define dmgtitlescreen_TILE_COUNT 216
#define dmgtitlescreen_PALETTE_COUNT 1
#define dmgtitlescreen_MAP_ATTRIBUTES 0
#define dmgtitlescreen_TILE_PALS dmgtitlescreen_tile_pals

BANKREF_EXTERN(dmgtitlescreen)

extern const palette_color_t dmgtitlescreen_palettes[4];
extern const uint8_t dmgtitlescreen_tiles[3456];

extern const unsigned char dmgtitlescreen_map[360];
extern const unsigned char* dmgtitlescreen_tile_pals[216];

#endif