/*

 DOWN_LEFT_TILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 16
   Tile set      : Z:\home\cavenderbi\Downloads\gbtd\bricks.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define up_left_tilesetWidth 20
#define up_left_tilesetHeight 16
#define up_left_tilesetBank 0

extern unsigned char down_left_tileset[];

/* End of DOWN_LEFT_TILEMAP.H */
