/*

 DOWN_RIGHT_TILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 16
   Tile set      : Z:\home\cavenderbi\Downloads\gbtd\bricks.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 20
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define down_right_tilesetWidth 20
#define down_right_tilesetHeight 16
#define down_right_tilesetBank 0

extern unsigned char down_right_tileset[];

/* End of DOWN_RIGHT_TILEMAP.H */
