/*

 HEART.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char heart[] =
{
  0x6C,0x6C,0x9E,0xF2,0x86,0xFA,0x44,0x7C,
  0x28,0x38,0x10,0x10,0x00,0x00,0x00,0x00,
  0x6C,0x6C,0x92,0xF2,0x82,0xF2,0x44,0x74,
  0x28,0x38,0x10,0x10,0x00,0x00,0x00,0x00
};

/* End of HEART.C */
