//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_hearts_H
#define METASPRITE_hearts_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define hearts_TILE_ORIGIN 0
#define hearts_TILE_H 8
#define hearts_WIDTH 8
#define hearts_HEIGHT 24
#define hearts_TILE_COUNT 3
#define hearts_MAP_ATTRIBUTES 0
#define hearts_TILE_PALS hearts_tile_pals

BANKREF_EXTERN(hearts)

extern const palette_color_t hearts_palettes[4];
extern const uint8_t hearts_tiles[48];

extern const unsigned char hearts_map[3];
extern const unsigned char* hearts_tile_pals[3];

#endif