/*

 HEART.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define heartBank 0

/* Super Gameboy palette 0 */
#define heartSGBPal0c0 6076
#define heartSGBPal0c1 8935
#define heartSGBPal0c2 6596
#define heartSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define heartSGBPal1c0 6076
#define heartSGBPal1c1 8935
#define heartSGBPal1c2 6596
#define heartSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define heartSGBPal2c0 6076
#define heartSGBPal2c1 8935
#define heartSGBPal2c2 6596
#define heartSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define heartSGBPal3c0 6076
#define heartSGBPal3c1 8935
#define heartSGBPal3c2 6596
#define heartSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define heartCGBPal0c0 32767
#define heartCGBPal0c1 20126
#define heartCGBPal0c2 31
#define heartCGBPal0c3 15

/* Gameboy Color palette 1 */
#define heartCGBPal1c0 6076
#define heartCGBPal1c1 8935
#define heartCGBPal1c2 6596
#define heartCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define heartCGBPal2c0 6076
#define heartCGBPal2c1 8935
#define heartCGBPal2c2 6596
#define heartCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define heartCGBPal3c0 6076
#define heartCGBPal3c1 8935
#define heartCGBPal3c2 6596
#define heartCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define heartCGBPal4c0 6076
#define heartCGBPal4c1 8935
#define heartCGBPal4c2 6596
#define heartCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define heartCGBPal5c0 6076
#define heartCGBPal5c1 8935
#define heartCGBPal5c2 6596
#define heartCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define heartCGBPal6c0 6076
#define heartCGBPal6c1 8935
#define heartCGBPal6c2 6596
#define heartCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define heartCGBPal7c0 6076
#define heartCGBPal7c1 8935
#define heartCGBPal7c2 6596
#define heartCGBPal7c3 5344

/* CGB palette entries. */
#define heartCGB0 0
#define heartCGB1 0
/* Start of tile array. */
extern unsigned char heart[];

/* End of HEART.H */
