//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_HUD_H
#define METASPRITE_HUD_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define HUD_TILE_ORIGIN 0
#define HUD_TILE_H 8
#define HUD_WIDTH 160
#define HUD_HEIGHT 16
#define HUD_TILE_COUNT 15
#define HUD_MAP_ATTRIBUTES 0
#define HUD_TILE_PALS HUD_tile_pals

BANKREF_EXTERN(HUD)

extern const palette_color_t HUD_palettes[16];
extern const uint8_t HUD_tiles[240];

extern const unsigned char HUD_map[40];
extern const unsigned char* HUD_tile_pals[15];

#endif