//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_knight_walk_down_H
#define METASPRITE_knight_walk_down_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define knight_walk_down_TILE_H 16
#define knight_walk_down_WIDTH 16
#define knight_walk_down_HEIGHT 32
#define knight_walk_down_TILE_COUNT 4
#define knight_walk_down_PIVOT_X 8
#define knight_walk_down_PIVOT_Y 16
#define knight_walk_down_PIVOT_W 16
#define knight_walk_down_PIVOT_H 32

BANKREF_EXTERN(knight_walk_down)

extern const palette_color_t knight_walk_down_palettes[4];
extern const uint8_t knight_walk_down_tiles[128];

extern const metasprite_t* const knight_walk_down_metasprites[1];

#endif