//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_knight_H
#define METASPRITE_knight_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define knight_TILE_H 16
#define knight_WIDTH 16
#define knight_HEIGHT 96
#define knight_TILE_COUNT 12
#define knight_PIVOT_X 8
#define knight_PIVOT_Y 48
#define knight_PIVOT_W 16
#define knight_PIVOT_H 96

BANKREF_EXTERN(knight)

extern const palette_color_t knight_palettes[4];
extern const uint8_t knight_tiles[384];

extern const metasprite_t* const knight_metasprites[1];

#endif