//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_knight_walk_up_H
#define METASPRITE_knight_walk_up_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define knight_walk_up_TILE_H 16
#define knight_walk_up_WIDTH 16
#define knight_walk_up_HEIGHT 32
#define knight_walk_up_TILE_COUNT 4
#define knight_walk_up_PIVOT_X 8
#define knight_walk_up_PIVOT_Y 16
#define knight_walk_up_PIVOT_W 16
#define knight_walk_up_PIVOT_H 32

BANKREF_EXTERN(knight_walk_up)

extern const palette_color_t knight_walk_up_palettes[4];
extern const uint8_t knight_walk_up_tiles[128];

extern const metasprite_t* const knight_walk_up_metasprites[1];

#endif