//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_knight_walk_up_H
#define METASPRITE_knight_walk_up_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define knight_walk_up_TILE_ORIGIN 0
#define knight_walk_up_TILE_H 8
#define knight_walk_up_WIDTH 16
#define knight_walk_up_HEIGHT 16
#define knight_walk_up_TILE_COUNT 7
#define knight_walk_up_PIVOT_X 8
#define knight_walk_up_PIVOT_Y 8
#define knight_walk_up_PIVOT_W 16
#define knight_walk_up_PIVOT_H 16

BANKREF_EXTERN(knight_walk_up)

extern const palette_color_t knight_walk_up_palettes[4];
extern const uint8_t knight_walk_up_tiles[112];

extern const metasprite_t* const knight_walk_up_metasprites[2];

#endif