//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(mask)

const palette_color_t mask_palettes[4] = {
	RGB8(0, 0, 0), RGB8(0, 192, 255), RGB8(255, 0, 0), RGB8(89, 0, 0)
};

const uint8_t mask_tiles[16] = {
	0x7e,0x7e,0x81,0xff,0xe7,0xff,0xa5,0xff,0xff,0x00,0xff,0x00,0xff,0x81,0x7e,0x7e
};

const metasprite_t mask_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, 0), METASPR_TERM
};

const metasprite_t* const mask_metasprites[1] = {
	mask_metasprite0
};
