//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_mask_H
#define METASPRITE_mask_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define mask_TILE_ORIGIN 0
#define mask_TILE_H 8
#define mask_WIDTH 8
#define mask_HEIGHT 8
#define mask_TILE_COUNT 1
#define mask_PIVOT_X 4
#define mask_PIVOT_Y 4
#define mask_PIVOT_W 8
#define mask_PIVOT_H 8

BANKREF_EXTERN(mask)

extern const palette_color_t mask_palettes[4];
extern const uint8_t mask_tiles[16];

extern const metasprite_t* const mask_metasprites[1];

#endif