//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_middletop_H
#define METASPRITE_middletop_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define middletop_TILE_ORIGIN 33
#define middletop_TILE_H 8
#define middletop_WIDTH 160
#define middletop_HEIGHT 128
#define middletop_TILE_COUNT 0
#define middletop_PALETTE_COUNT 1
#define middletop_MAP_ATTRIBUTES 0
#define middletop_TILE_PALS middletop_tile_pals

BANKREF_EXTERN(middletop)


extern const unsigned char middletop_map[320];

#endif