//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_middlebottom_H
#define METASPRITE_middlebottom_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define middlebottom_TILE_ORIGIN 33
#define middlebottom_TILE_H 8
#define middlebottom_WIDTH 160
#define middlebottom_HEIGHT 128
#define middlebottom_TILE_COUNT 0
#define middlebottom_PALETTE_COUNT 1
#define middlebottom_MAP_ATTRIBUTES 0
#define middlebottom_TILE_PALS middlebottom_tile_pals

BANKREF_EXTERN(middlebottom)


extern const unsigned char middlebottom_map[320];

#endif