//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_middleright_H
#define METASPRITE_middleright_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define middleright_TILE_ORIGIN 33
#define middleright_TILE_H 8
#define middleright_WIDTH 160
#define middleright_HEIGHT 128
#define middleright_TILE_COUNT 0
#define middleright_PALETTE_COUNT 1
#define middleright_MAP_ATTRIBUTES 0
#define middleright_TILE_PALS middleright_tile_pals

BANKREF_EXTERN(middleright)


extern const unsigned char middleright_map[341];

#endif