//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_middle_H
#define METASPRITE_middle_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define middle_TILE_ORIGIN 33
#define middle_TILE_H 8
#define middle_WIDTH 160
#define middle_HEIGHT 128
#define middle_TILE_COUNT 0
#define middle_PALETTE_COUNT 1
#define middle_MAP_ATTRIBUTES 0
#define middle_TILE_PALS middle_tile_pals

BANKREF_EXTERN(middle)


extern const unsigned char middle_map[341];

#endif