/*

 PLAYER_BASIC_PROJ.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char player_basic_proj[] =
{
  0x70,0x70,0x8C,0xFC,0xBB,0xC7,0x8C,0xFC,
  0x70,0x70,0x00,0x00,0x00,0x00,0x00,0x00,
  0x70,0x70,0x88,0xF8,0xA8,0xD8,0xA8,0xD8,
  0x70,0x50,0x50,0x70,0x20,0x20,0x20,0x20
};

/* End of PLAYER_BASIC_PROJ.C */
