//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_powerorb_H
#define METASPRITE_powerorb_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define powerorb_TILE_ORIGIN 0
#define powerorb_TILE_H 8
#define powerorb_WIDTH 8
#define powerorb_HEIGHT 8
#define powerorb_TILE_COUNT 1
#define powerorb_PALETTE_COUNT 1

BANKREF_EXTERN(powerorb)

extern const palette_color_t powerorb_palettes[4];
extern const uint8_t powerorb_tiles[16];


#endif