//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(powerorb)

const palette_color_t powerorb_palettes[4] = {
	RGB8(0, 0, 0), RGB8(250, 220, 196), RGB8(250, 169, 102), RGB8(255, 115, 0)
};

const uint8_t powerorb_tiles[16] = {
	0x3c,0x3c,0x42,0x7e,0x81,0xff,0x99,0xe7,0x99,0xe7,0x81,0xff,0x42,0x7e,0x3c,0x3c
};

