//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_singleleft_H
#define METASPRITE_singleleft_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define singleleft_TILE_ORIGIN 0
#define singleleft_TILE_H 16
#define singleleft_WIDTH 160
#define singleleft_HEIGHT 128
#define singleleft_TILE_COUNT 14
#define singleleft_PIVOT_X 80
#define singleleft_PIVOT_Y 64
#define singleleft_PIVOT_W 160
#define singleleft_PIVOT_H 128

BANKREF_EXTERN(singleleft)

extern const palette_color_t singleleft_palettes[4];
extern const uint8_t singleleft_tiles[224];

extern const metasprite_t* const singleleft_metasprites[1];

#endif