//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_singleright_H
#define METASPRITE_singleright_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define singleright_TILE_ORIGIN 33
#define singleright_TILE_H 8
#define singleright_WIDTH 160
#define singleright_HEIGHT 128
#define singleright_TILE_COUNT 0
#define singleright_PALETTE_COUNT 1
#define singleright_MAP_ATTRIBUTES 0
#define singleright_TILE_PALS singleright_tile_pals

BANKREF_EXTERN(singleright)


extern const unsigned char singleright_map[341];

#endif