//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_singleleft_H
#define METASPRITE_singleleft_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define singleleft_TILE_ORIGIN 33
#define singleleft_TILE_H 8
#define singleleft_WIDTH 160
#define singleleft_HEIGHT 128
#define singleleft_TILE_COUNT 0
#define singleleft_PALETTE_COUNT 1
#define singleleft_MAP_ATTRIBUTES 0
#define singleleft_TILE_PALS singleleft_tile_pals

BANKREF_EXTERN(singleleft)


extern const unsigned char singleleft_map[341];

#endif