//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_singledown_H
#define METASPRITE_singledown_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define singledown_TILE_ORIGIN 33
#define singledown_TILE_H 8
#define singledown_WIDTH 160
#define singledown_HEIGHT 128
#define singledown_TILE_COUNT 0
#define singledown_PALETTE_COUNT 1
#define singledown_MAP_ATTRIBUTES 0
#define singledown_TILE_PALS singledown_tile_pals

BANKREF_EXTERN(singledown)


extern const unsigned char singledown_map[320];

#endif