//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_singleright_H
#define METASPRITE_singleright_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define singleright_TILE_ORIGIN 0
#define singleright_TILE_H 16
#define singleright_WIDTH 160
#define singleright_HEIGHT 128
#define singleright_TILE_COUNT 14
#define singleright_PIVOT_X 80
#define singleright_PIVOT_Y 64
#define singleright_PIVOT_W 160
#define singleright_PIVOT_H 128

BANKREF_EXTERN(singleright)

extern const palette_color_t singleright_palettes[4];
extern const uint8_t singleright_tiles[224];

extern const metasprite_t* const singleright_metasprites[1];

#endif