//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_singleup_H
#define METASPRITE_singleup_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define singleup_TILE_ORIGIN 33
#define singleup_TILE_H 8
#define singleup_WIDTH 160
#define singleup_HEIGHT 128
#define singleup_TILE_COUNT 0
#define singleup_PALETTE_COUNT 1
#define singleup_MAP_ATTRIBUTES 0
#define singleup_TILE_PALS singleup_tile_pals

BANKREF_EXTERN(singleup)


extern const unsigned char singleup_map[341];

#endif