//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sketch_titlescreen_H
#define METASPRITE_sketch_titlescreen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sketch_titlescreen_TILE_ORIGIN 0
#define sketch_titlescreen_TILE_H 8
#define sketch_titlescreen_WIDTH 160
#define sketch_titlescreen_HEIGHT 144
#define sketch_titlescreen_TILE_COUNT 222
#define sketch_titlescreen_MAP_ATTRIBUTES 0
#define sketch_titlescreen_TILE_PALS sketch_titlescreen_tile_pals

BANKREF_EXTERN(sketch_titlescreen)

extern const palette_color_t sketch_titlescreen_palettes[4];
extern const uint8_t sketch_titlescreen_tiles[3552];

extern const unsigned char sketch_titlescreen_map[360];
extern const unsigned char* sketch_titlescreen_tile_pals[222];

#endif