//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_straightvertical_H
#define METASPRITE_straightvertical_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define straightvertical_TILE_ORIGIN 0
#define straightvertical_TILE_H 16
#define straightvertical_WIDTH 160
#define straightvertical_HEIGHT 128
#define straightvertical_TILE_COUNT 12
#define straightvertical_PIVOT_X 80
#define straightvertical_PIVOT_Y 64
#define straightvertical_PIVOT_W 160
#define straightvertical_PIVOT_H 128

BANKREF_EXTERN(straightvertical)

extern const palette_color_t straightvertical_palettes[4];
extern const uint8_t straightvertical_tiles[192];

extern const metasprite_t* const straightvertical_metasprites[1];

#endif