//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_straightvertical_H
#define METASPRITE_straightvertical_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define straightvertical_TILE_ORIGIN 33
#define straightvertical_TILE_H 8
#define straightvertical_WIDTH 160
#define straightvertical_HEIGHT 128
#define straightvertical_TILE_COUNT 0
#define straightvertical_PALETTE_COUNT 1
#define straightvertical_MAP_ATTRIBUTES 0
#define straightvertical_TILE_PALS straightvertical_tile_pals

BANKREF_EXTERN(straightvertical)


extern const unsigned char straightvertical_map[341];

#endif