//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_test_fourrooms_H
#define METASPRITE_test_fourrooms_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define test_fourrooms_TILE_ORIGIN 0
#define test_fourrooms_TILE_H 8
#define test_fourrooms_WIDTH 320
#define test_fourrooms_HEIGHT 256
#define test_fourrooms_TILE_COUNT 21
#define test_fourrooms_MAP_ATTRIBUTES 0
#define test_fourrooms_TILE_PALS test_fourrooms_tile_pals

BANKREF_EXTERN(test_fourrooms)

extern const palette_color_t test_fourrooms_palettes[4];
extern const uint8_t test_fourrooms_tiles[336];

extern const unsigned char test_fourrooms_map[1280];
extern const unsigned char* test_fourrooms_tile_pals[21];

#endif