//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_test_goombah_H
#define METASPRITE_test_goombah_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define test_goombah_TILE_ORIGIN 0
#define test_goombah_TILE_H 8
#define test_goombah_WIDTH 16
#define test_goombah_HEIGHT 16
#define test_goombah_TILE_COUNT 3
#define test_goombah_PIVOT_X 8
#define test_goombah_PIVOT_Y 8
#define test_goombah_PIVOT_W 16
#define test_goombah_PIVOT_H 16

BANKREF_EXTERN(test_goombah)

extern const palette_color_t test_goombah_palettes[4];
extern const uint8_t test_goombah_tiles[48];

extern const metasprite_t* const test_goombah_metasprites[2];

#endif