//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_test_fourrooms_H
#define METASPRITE_test_fourrooms_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define test_fourrooms_TILE_ORIGIN 0
#define test_fourrooms_TILE_H 8
#define test_fourrooms_WIDTH 320
#define test_fourrooms_HEIGHT 256
#define test_fourrooms_TILE_COUNT 21
#define test_fourrooms_PALETTE_COUNT 1

BANKREF_EXTERN(test_fourrooms)

extern const palette_color_t test_fourrooms_palettes[4];
extern const uint8_t test_fourrooms_tiles[336];


#endif