/*

 TESTROOM_TILEMAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 16
   Tile set      : bruh.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 20
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define testroom2Width 20
#define testroom2Height 16
#define testroom2Bank 0

extern unsigned char testroom2[];

/* End of TESTROOM_TILEMAP2.H */
