/*

 TESTROOMBIG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 32
   Tile set      : Z:\home\gato\Documents\Capstone\saves\bruh.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 20
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define testroom_bigWidth 40
#define testroom_bigHeight 32
#define testroom_bigBank 0

extern unsigned char testroom_big[];

/* End of TESTROOMBIG.H */
