//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_titlescreen_H
#define METASPRITE_titlescreen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define titlescreen_TILE_ORIGIN 0
#define titlescreen_TILE_H 8
#define titlescreen_WIDTH 160
#define titlescreen_HEIGHT 144
#define titlescreen_TILE_COUNT 223
#define titlescreen_PALETTE_COUNT 7
#define titlescreen_MAP_ATTRIBUTES 0
#define titlescreen_TILE_PALS titlescreen_tile_pals

BANKREF_EXTERN(titlescreen)

extern const palette_color_t titlescreen_palettes[28];
extern const uint8_t titlescreen_tiles[3568];

extern const unsigned char titlescreen_map[360];
extern const unsigned char* titlescreen_tile_pals[223];

#endif