//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_topleft_H
#define METASPRITE_topleft_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define topleft_TILE_ORIGIN 0
#define topleft_TILE_H 8
#define topleft_WIDTH 160
#define topleft_HEIGHT 128
#define topleft_TILE_COUNT 12
#define topleft_MAP_ATTRIBUTES 0
#define topleft_TILE_PALS topleft_tile_pals

BANKREF_EXTERN(topleft)

extern const palette_color_t topleft_palettes[4];
extern const uint8_t topleft_tiles[192];

extern const unsigned char topleft_map[320];
extern const unsigned char* topleft_tile_pals[12];

#endif