//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_topright_H
#define METASPRITE_topright_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define topright_TILE_ORIGIN 33
#define topright_TILE_H 8
#define topright_WIDTH 160
#define topright_HEIGHT 128
#define topright_TILE_COUNT 0
#define topright_PALETTE_COUNT 1
#define topright_MAP_ATTRIBUTES 0
#define topright_TILE_PALS topright_tile_pals

BANKREF_EXTERN(topright)


extern const unsigned char topright_map[341];

#endif