/*

 UP_RIGHT_TILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 16
   Tile set      : Z:\home\cavenderbi\Downloads\gbtd\bricks.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 20
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define up_right_tilemapWidth 20
#define up_right_tilemapHeight 16
#define up_right_tilemapBank 0

extern unsigned char up_right_tilemap[];

/* End of UP_RIGHT_TILEMAP.H */
