//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_wizard_walk_side_H
#define METASPRITE_wizard_walk_side_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define wizard_walk_side_TILE_ORIGIN 0
#define wizard_walk_side_TILE_H 8
#define wizard_walk_side_WIDTH 16
#define wizard_walk_side_HEIGHT 16
#define wizard_walk_side_TILE_COUNT 8
#define wizard_walk_side_PIVOT_X 8
#define wizard_walk_side_PIVOT_Y 8
#define wizard_walk_side_PIVOT_W 16
#define wizard_walk_side_PIVOT_H 16

BANKREF_EXTERN(wizard_walk_side)

extern const palette_color_t wizard_walk_side_palettes[4];
extern const uint8_t wizard_walk_side_tiles[128];

extern const metasprite_t* const wizard_walk_side_metasprites[2];

#endif