/*

 TESTROOMBIG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 32
   Tile set      : Z:\home\gato\Documents\Capstone\saves\bruh.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BigWidth 40
#define BigHeight 32
#define BigBank 0

extern unsigned char Big[];

/* End of TESTROOMBIG.H */
