//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_middleleft_H
#define METASPRITE_middleleft_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define middleleft_TILE_ORIGIN 33
#define middleleft_TILE_H 8
#define middleleft_WIDTH 160
#define middleleft_HEIGHT 128
#define middleleft_TILE_COUNT 0
#define middleleft_PALETTE_COUNT 1
#define middleleft_MAP_ATTRIBUTES 0
#define middleleft_TILE_PALS middleleft_tile_pals

BANKREF_EXTERN(middleleft)


extern const unsigned char middleleft_map[320];

#endif