//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_test_logo_H
#define METASPRITE_test_logo_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define test_logo_TILE_ORIGIN 0
#define test_logo_TILE_H 8
#define test_logo_WIDTH 160
#define test_logo_HEIGHT 144
#define test_logo_TILE_COUNT 75
#define test_logo_PALETTE_COUNT 1
#define test_logo_MAP_ATTRIBUTES test_logo_map_attributes
#define test_logo_TILE_PALS 0

BANKREF_EXTERN(test_logo)

extern const palette_color_t test_logo_palettes[4];
extern const uint8_t test_logo_tiles[1200];

extern const unsigned char test_logo_map[360];
extern const unsigned char test_logo_map_attributes[360];

#endif