//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_straighthorizontal_H
#define METASPRITE_straighthorizontal_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define straighthorizontal_TILE_ORIGIN 33
#define straighthorizontal_TILE_H 8
#define straighthorizontal_WIDTH 160
#define straighthorizontal_HEIGHT 128
#define straighthorizontal_TILE_COUNT 0
#define straighthorizontal_PALETTE_COUNT 1
#define straighthorizontal_MAP_ATTRIBUTES 0
#define straighthorizontal_TILE_PALS straighthorizontal_tile_pals

BANKREF_EXTERN(straighthorizontal)


extern const unsigned char straighthorizontal_map[320];

#endif