//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_wizard_walk_down_H
#define METASPRITE_wizard_walk_down_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define wizard_walk_down_TILE_ORIGIN 0
#define wizard_walk_down_TILE_H 8
#define wizard_walk_down_WIDTH 16
#define wizard_walk_down_HEIGHT 16
#define wizard_walk_down_TILE_COUNT 4
#define wizard_walk_down_PIVOT_X 8
#define wizard_walk_down_PIVOT_Y 8
#define wizard_walk_down_PIVOT_W 16
#define wizard_walk_down_PIVOT_H 16

BANKREF_EXTERN(wizard_walk_down)

extern const palette_color_t wizard_walk_down_palettes[4];
extern const uint8_t wizard_walk_down_tiles[64];

extern const metasprite_t* const wizard_walk_down_metasprites[2];

#endif