//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_frost_H
#define METASPRITE_frost_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define frost_TILE_ORIGIN 0
#define frost_TILE_H 8
#define frost_WIDTH 16
#define frost_HEIGHT 16
#define frost_TILE_COUNT 4
#define frost_PALETTE_COUNT 1
#define frost_MAP_ATTRIBUTES 0
#define frost_TILE_PALS frost_tile_pals

BANKREF_EXTERN(frost)

extern const palette_color_t frost_palettes[4];
extern const uint8_t frost_tiles[64];

extern const unsigned char frost_map[4];
extern const unsigned char* frost_tile_pals[4];

#endif