//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_shock_H
#define METASPRITE_shock_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define shock_TILE_ORIGIN 0
#define shock_TILE_H 8
#define shock_WIDTH 16
#define shock_HEIGHT 16
#define shock_TILE_COUNT 4
#define shock_PALETTE_COUNT 1
#define shock_MAP_ATTRIBUTES 0
#define shock_TILE_PALS shock_tile_pals

BANKREF_EXTERN(shock)

extern const palette_color_t shock_palettes[4];
extern const uint8_t shock_tiles[64];

extern const unsigned char shock_map[4];
extern const unsigned char* shock_tile_pals[4];

#endif