/*

 HUD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : Z:\home\cavenderbi\Downloads\gbtd\hud.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hud_tilemapWidth 20
#define hud_tilemapHeight 2
#define hud_tilemapBank 0

extern unsigned char hud_tilemap[];

/* End of HUD.H */
