/*

 SCROLL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 16
   Tile set      : Z:\home\cavenderbi\Downloads\gbtd\scroll.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define scroll_tilemapWidth 64
#define scroll_tilemapHeight 16
#define scroll_tilemapBank 0

extern unsigned char scroll_tilemap[];

/* End of SCROLL.H */
