/*

 TEST.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 16
   Tile set      : Z:\home\cavenderbi\Downloads\gbtd\test.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 21
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define test_tilemapWidth 20
#define test_tilemapHeight 16
#define test_tilemapBank 0

extern unsigned char test_tilemap[];

/* End of TEST.H */
