/*
 TEST_PROJECTILE.H
 Include File.
 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3
  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.
  Convert to metatiles : No.
 This file was generated by GBTD v2.2
*/


/* Bank of tiles. */
#define test_projectileBank 0
/* Start of tile array. */
extern unsigned char test_projectile[];

/* End of TEST_PROJECTILE.H */